version: '3'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile-app1
    ports:
      - "8001:8001"
    restart: always

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile-app2
    ports:
      - "8002:8002"
    restart: always